import React, { Component } from 'react';

class PrivacyPolicy extends Component {
	constructor(props) {
    super(props);
	    this.state = {
	     
	    };
    }	

    componentDidMount() {
      window.scrollTo(0,0);
    }
    
  render() {
     
    return (      
		<section className="termsCondition-page">
          <div className="container">
            <div className="cms-page">
              <h1 className="text-center">Privacy Policy</h1>
                <h4>Effective date: May 30, 2019</h4>
                <p>DLD LLC (“us,” “we,” or “our”) operates the www.dld-vip.com website (the “Service”). This page informs you of our policies about the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. You agree to the collection and use of information, as explained by this policy, by using the Service.</p>
                <h4>Definitions</h4>
                <div>
                    <p><b>Service</b></p>
                    <p>Service is the www.dld-vip.com website operated by DLD LLC.</p>
                    <p><b>Personal Data</b></p>
                    <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                    <p><b>Usage Data</b></p>
                    <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    <p><b>Cookies</b></p>
                    <p>Cookies are small files stored on your device (computer or mobile device).</p>
                    <p><b>Data Controller</b></p>
                    <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                    <p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
                    <p><b>Data Processors (or Service Providers)</b></p>
                    <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.<br/>
                        We may use the services of various Service Providers in order to process your data more effectively.</p>
                    <p><b>Data Subject (or User)</b></p>
                    <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
                </div>



                <h4>Information Collection and Use</h4>
                <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

                <h4>Types of Data Collected</h4>
                <p><b>Personal Data</b></p>
                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may interest you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</p>
                <p>Personally identifiable information and Personal Data may include, but is not limited to:</p>
                <ul>
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Cookies and Usage Data</li>
                </ul>

                <p><b>Usage Data</b></p>

                <p>We may also collect information on how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p><b>Location Data</b></p>
                <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location services when you use our Service at any time through your device settings.</p>
                <p><b>Tracking Cookies Data</b></p>
                <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to show when a cookie is being sent. That said, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use:</p>

                <ul>
                    <li><b>Session Cookies.</b> We use Session Cookies to operate our Service.</li>
                    <li><b>Preference Cookies.</b> We use Preference Cookies to remember your preferences and various settings.</li>
                    <li><b>Security Cookies.</b> We use Security Cookies for security purposes.</li>
                </ul>

                <h4>Use of Data</h4>

                <p>DLD LLC uses the collected data for various purposes:</p>
                <ul>
                    <li>To provide and maintain our Service</li>
                    <li>To notify you about changes to our Service</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                    <li>To provide customer support</li>
                    <li>To gather analysis or valuable information so that we can improve our Service</li>
                    <li>To monitor the usage of our Service</li>
                    <li>To detect, prevent and address technical issues</li>
                    <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are like those that you have already purchased or inquired about unless you have opted not to receive this information</li>
                </ul>

                <h4>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</h4>
                <p>If you are from the European Economic Area (EEA), DLD LLC legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it. DLD LLC may process your Personal Data because:</p>
                 <ul>
                     <li>We need to perform a contract with you</li>
                     <li>You have given us permission to do so</li>
                     <li>The processing is in our legitimate interests and it is not overridden by your rights</li>
                     <li>For payment processing purposes</li>
                     <li>To comply with the law</li>
                </ul>

                <h4>Retention of Data</h4>
                <p>DLD LLC will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data as needed to comply with our legal obligations (for example, if we need to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies. DLD LLC will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter time period, unless this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>

                <h4>Transfer of Data</h4>
                <p>Your information, including Personal Data, may be transferred to—and maintained on—computers located outside your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside United States and choose to provide information to us, we transfer the data, including Personal Data, to United States and process it there. Your consent to this Privacy Policy followed by your submission of that information represents your agreement to that transfer. DLD LLC will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

                <h4>Disclosure of Data</h4>
                <p><b>Business Transaction</b></p>
                <p>If DLD LLC is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                <p><b>Disclosure for Law Enforcement</b></p>
                <p>In some cases, DLD LLC may need to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
                <p><b>Legal Requirements</b></p>
                <p>DLD LLC may disclose your Personal Data in the good-faith belief that this action is necessary to:</p>
                <ul>
                    <li>To comply with a legal obligation</li>
                    <li>To protect and defend the rights or property of DLD LLC</li>
                    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>To protect the personal safety of users of the Service or the public</li>
                    <li>To protect against legal liability</li>
                </ul>

                <h4>Security of Data</h4>
                <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                <h4>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h4>
                <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. DLD LLC aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data. If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us. Sometimes you have these data protection rights:</p>

                <div>
                    <p><b>The right to access, update or delete the information we have on you.</b> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</p>
                    <p><b>The right of rectification.</b> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
                    <p><b>The right to object.</b> You have the right to object to our processing of your Personal Data.</p>
                    <p><b>The right of restriction.</b> You have the right to request that we restrict the processing of your personal information.</p>
                    <p><b>The right to data portability.</b> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</p>
                <p><b>The right to withdraw consent.</b> You also have the right to withdraw your consent at any time where DLD LLC relied on your consent to process your personal information.</p>
                </div>

                <p>We may ask you to verify your identity before responding to such requests. You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

                <h4>Service Providers</h4>
                <p>We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), provide the Service on our behalf, perform Service-related services or help us analyze how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

                <h4>Analytics</h4>
                <p>We may use third-party Service Providers to monitor and analyze the use of our Service. For example, we use Google Analytics. Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network. You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity. For more information on the privacy practices of Google, please visit the <a href="https://policies.google.com/privacy?hl=en" target="_blank">Google Privacy Terms web page</a></p>
                <h4>Payments</h4>
                <p>We may provide paid products, services, or both within the Service. In that case, we use third-party services for payment processing (e.g., payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information. We work with Authorize.net for payment processing. Their Privacy Policy can be viewed at <a href="https://www.authorize.net/company/privacy/"  target="_blank">https://www.authorize.net/company/privacy/</a></p>
                <h4>Children's Privacy</h4>
                <p>Our Service does not address anyone under the age of 18 (“Children”). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you know that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
                <h4>Changes to This Privacy Policy</h4>
                <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know by email, a prominent notice on our Service, or both before the change becoming effective and update the “effective date” at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                <h4>Contact Us</h4>
                <p>If you have any questions about this Privacy Policy, please contact us:</p>
                <p>By email: <b>admin@thedldllc.com</b></p>

            </div>
          </div>
		</section>    
    )
  }
}

export default PrivacyPolicy;