export const CardErrorCode = {
  "0": "Unknown Error.",
  "1": "This transaction has been approved.",
  "2": "This transaction has been declined.",
  "3": "This transaction has been declined.",
  "4": "This transaction has been declined.",
  "5": "A valid amount is required.",
  "6": "The credit card number is invalid.",
  "7": "Credit card expiration date is invalid.",
  "8": "The credit card has expired.",
  "9": "The ABA code is invalid",
  "10": "The account number is invalid",
  "11": "A duplicate transaction has been submitted.",
  "12": "An authorization code is required but not present.",
  "13":
    "The merchant login ID or password is invalid or the account is inactive.",
  "14": "The referrer, relay response or receipt link URL is invalid.",
  "15": "The transaction ID is invalid or not present.",
  "16": "The transaction cannot be found.",
  "17": "The merchant does not accept this type of credit card.",
  "18": "ACH transactions are not accepted by this merchant.",
  "19": "An error occurred during processing. Please try again.",
  "20": "An error occurred during processing. Please try again.",
  "21": "An error occurred during processing. Please try again.",
  "22": "An error occurred during processing. Please try again.",
  "23": "An error occurred during processing. Please try again.",
  "24":
    "The Elavon bank number or terminal ID is incorrect. Call Merchant Service Provider.",
  "25": "An error occurred during processing. Please try again.",
  "26": "An error occurred during processing. Please try again.",
  "27":
    "The transaction has been declined because of an AVS mismatch. The address provided does not match billing address of cardholder.",
  "28": "The merchant does not accept this type of credit card.",
  "29":
    "The Paymentech identification numbers are incorrect. Call Merchant Service Provider.",
  "30":
    "The configuration with processor is invalid. Call Merchant Service Provider.",
  "31":
    "The FDC Merchant ID or Terminal ID is incorrect. Call Merchant Service Provider.",
  "32": "The merchant password is invalid or not present.",
  "33": "%s cannot be left blank.",
  "34":
    "The VITAL identification numbers are incorrect. Call Merchant Service Provider.",
  "35": "An error occurred during processing. Call Merchant Service Provider.",
  "36": "The authorization was approved but settlement failed.",
  "37": "The credit card number is invalid.",
  "38":
    "The Global Payment System identification numbers are incorrect. Call Merchant Service Provider.",
  "39":
    "The supplied currency code is either invalid, not supported, not allowed for this merchant or doesnt have an exchange rate.",
  "40": "This transaction must be encrypted.",
  "41": "This transaction has been declined.",
  "42": "There is missing or invalid information in a required field.",
  "43":
    "The merchant was incorrectly set up at the processor. Call Merchant Service Provider.",
  "44": "This transaction has been declined.",
  "45": "This transaction has been declined.",
  "46":
    "Your session has expired or does not exist. You must log in again to continue working.",
  "47":
    "The amount requested for settlement cannot be greater than the original amount authorized.",
  "48": "This processor does not accept partial reversals.",
  "49":
    "The transaction amount submitted was greater than the maximum amount allowed.",
  "50": "This transaction is awaiting settlement and cannot be refunded.",
  "51":
    "The sum of all credits against this transaction is greater than the original transaction amount.",
  "52":
    "The transaction was authorized but the client could not be notified; it will not be settled.",
  "53": "The transaction type is invalid for ACH transactions.",
  "54":
    "The referenced transaction does not meet the criteria for issuing a credit.",
  "55":
    "The sum of credits against the referenced transaction would exceed original debit amount.",
  "56": "Credit card transactions are not accepted by this merchant.",
  "57": "An error occurred during processing. Please try again.",
  "58": "An error occurred during processing. Please try again.",
  "59": "An error occurred during processing. Please try again.",
  "60": "An error occurred during processing. Please try again.",
  "61": "An error occurred during processing. Please try again.",
  "62": "An error occurred during processing. Please try again.",
  "63": "An error occurred during processing. Please try again.",
  "64": "The referenced transaction was not approved.",
  "65": "This transaction has been declined.",
  "66": "This transaction cannot be accepted for processing.",
  "67": "The given transaction type is not supported for this merchant.",
  "68": "The version parameter is invalid",
  "69": "The transaction type is invalid",
  "70": "The transaction method is invalid.",
  "71": "The bank account type is invalid.",
  "72": "The authorization code is invalid.",
  "73": "The drivers license date of birth is invalid.",
  "74": "The duty amount is invalid.",
  "75": "The freight amount is invalid.",
  "76": "The tax amount is invalid.",
  "77": "The SSN or tax ID is invalid.",
  "78": "The card code is invalid.",
  "79": "The drivers license number is invalid.",
  "80": "The drivers license state is invalid.",
  "81": "The requested form type is invalid.",
  "82": "Scripts are only supported in version 2.5.",
  "83": "The requested script is either invalid or no longer supported.",
  "84": "The device type is invalid or missing.",
  "85": "The market type is invalid",
  "86": "The Response Format is invalid",
  "87": "Transactions of this market type cannot be processed on this system.",
  "88": "Track1 data is not in a valid format.",
  "89": "Track2 data is not in a valid format.",
  "90": "ACH transactions cannot be accepted by this system.",
  "91": "Version 2.5 is no longer supported.",
  "92": "The gateway no longer supports the requested method of integration.",
  "93": "A valid country is required.",
  "94": "The shipping state or country is invalid.",
  "95": "A valid state is required.",
  "96": "This country is not authorized for buyers.",
  "97": "This transaction cannot be accepted.",
  "98": "This transaction cannot be accepted.",
  "99": "This transaction cannot be accepted.",
  "100": "The eCheck type parameter is invalid.",
  "101":
    "The given name on the account and/or the account type does not match the actual account.",
  "102": "This request cannot be accepted.",
  "103": "This transaction cannot be accepted.",
  "104": "The transaction is currently under review.",
  "105": "The transaction is currently under review.",
  "106": "The transaction is currently under review.",
  "107": "The transaction is currently under review.",
  "108": "The transaction is currently under review.",
  "109": "The transaction is currently under review.",
  "110": "The transaction is currently under review.",
  "111": "A valid billing country is required.",
  "112": "A valid billing state/province is required.",
  "113": "The commercial card type is invalid.",
  "114":
    "The merchant account is in test mode. This automated payment will not be processed.",
  "115":
    "The merchant account is not active. This automated payment will not be processed.",
  "116": "The authentication indicator is invalid.",
  "117": "The cardholder authentication value is invalid.",
  "118":
    "The combination of card type, authentication indicator and cardholder authentication value is invalid.",
  "119":
    "Transactions having cardholder authentication values cannot be marked as recurring.",
  "120": "An error occurred during processing. Please try again.",
  "121": "An error occurred during processing. Please try again.",
  "122": "An error occurred during processing. Please try again.",
  "123":
    "This account has not been given the permission(s) required for this request.",
  "124": "This processor does not accept recurring transactions.",
  "125": "The surcharge amount is invalid.",
  "126": "The Tip amount is invalid.",
  "127":
    "The transaction resulted in an AVS mismatch. The address provided does not match billing address of cardholder.",
  "128": "This transaction cannot be processed.",
  "130": "This merchant account has been closed.",
  "131": "This transaction cannot be accepted at this time.",
  "132": "This transaction cannot be accepted at this time.",
  "141": "This transaction has been declined.",
  "145": "This transaction has been declined.",
  "152":
    "The transaction was authorized but the client could not be notified; it will not be settled.",
  "153": "There was an error processing the payment data.",
  "154": "Processing Apple Payments is not enabled for this merchant account.",
  "155":
    "This processor does not support this method of submitting payment data.",
  "156":
    "The cryptogram is either invalid or cannot be used in combination with other parameters.",
  "165": "This transaction has been declined.",
  "170": "An error occurred during processing. Please contact the merchant.",
  "171": "An error occurred during processing. Please contact the merchant.",
  "172": "An error occurred during processing. Please contact the merchant.",
  "173": "An error occurred during processing. Please contact the merchant.",
  "174": "The transaction type is invalid. Please contact the merchant.",
  "175": "This processor does not allow voiding of credits.",
  "180": "An error occurred during processing. Please try again.",
  "181": "An error occurred during processing. Please try again.",
  "182": "One or more of the sub-merchant values are invalid.",
  "183": "One or more of the required sub-merchant values are missing.",
  "184": "Invalid Token Requestor Name.",
  "185": "This transaction cannot be processed.",
  "186": "Invalid Token Requestor ID Length.",
  "187": "Invalid Token Requestor ECI Length.",
  "191": "This transaction has been declined.",
  "192": "An error occurred during processing. Please try again.",
  "193": "The transaction is currently under review.",
  "195":
    "One or more of the HTML type configuration fields do not appear to be safe.",
  "200": "This transaction has been declined",
  "201": "This transaction has been declined",
  "202": "This transaction has been declined",
  "203": "This transaction has been declined",
  "204": "This transaction has been declined",
  "205": "This transaction has been declined",
  "206": "This transaction has been declined.",
  "207": "This transaction has been declined",
  "208": "This transaction has been declined",
  "209": "This transaction has been declined",
  "210": "This transaction has been declined",
  "211": "This transaction has been declined",
  "212": "This transaction has been declined",
  "213": "This transaction has been declined",
  "214": "This transaction has been declined",
  "215": "This transaction has been declined",
  "216": "This transaction has been declined",
  "217": "This transaction has been declined",
  "218": "This transaction has been declined",
  "219": "This transaction has been declined",
  "220": "This transaction has been declined",
  "221": "This transaction has been declined",
  "222": "This transaction has been declined",
  "223": "This transaction has been declined",
  "224": "This transaction has been declined",
  "225": "This transaction cannot be processed.",
  "226": "This transaction cannot be processed.",
  "227": "This transaction cannot be processed.",
  "228": "This transaction cannot be processed.",
  "229": "Conversion rate for this card is available.",
  "230": "This transaction cannot be processed.",
  "231": "This transaction cannot be processed.",
  "232": "This transaction cannot be processed.",
  "233": "This transaction cannot be processed.",
  "234": "This transaction cannot be processed.",
  "235": "This transaction cannot be processed.",
  "236": "This transaction cannot be processed.",
  "237": "This transaction cannot be processed.",
  "238": "This transaction cannot be processed.",
  "239": "This transaction cannot be processed.",
  "240": "This transaction cannot be processed.",
  "241": "This transaction cannot be processed.",
  "242": "This transaction cannot be processed.",
  "243": "Recurring billing is not allowed for this eCheck.Net type.",
  "244": "This eCheck.Net type is not allowed for this Bank Account Type.",
  "245":
    "This eCheck.Net type is not allowed when using the payment gateway hosted payment form.",
  "246": "This eCheck.Net type is not allowed.",
  "247": "This eCheck.Net type is not allowed.",
  "248": "The check number is invalid.",
  "250": "This transaction has been declined.",
  "251": "This transaction has been declined.",
  "252": "Your order has been received. Thank you for your business!",
  "253": "Your order has been received. Thank you for your business!",
  "254": "This transaction has been declined.",
  "260": "Reversal not supported for this transaction type.",
  "261": "An error occurred during processing. Please try again.",
  "262": "The PayformMask is invalid.",
  "265": "This transaction cannot be processed.",
  "270": "Line item %1 is invalid.",
  "271":
    "The number of line items submitted is not allowed. A maximum of %1 line items can be submitted.",
  "280": "The auction platform name is invalid.",
  "281": "The auction platform ID is invalid.",
  "282": "The auction listing type is invalid.",
  "283": "The auction listing ID is invalid.",
  "284": "The auction seller ID is invalid.",
  "285": "The auction buyer ID is invalid.",
  "286": "One or more required auction values were not submitted.",
  "287":
    "The combination of auction platform ID and auction platform name is invalid.",
  "288": "This transaction cannot be accepted.",
  "289":
    "This processor does not accept zero dollar authorization for this card type.",
  "290": "There is one or more missing or invalid required fields.",
  "295":
    "The amount of this request was only partially approved on the given prepaid card. An additional payment is required to fulfill the balance of this transaction.",
  "296": "The specified SplitTenderID is invalid.",
  "297":
    "Transaction ID and Split Tender ID cannot both be used in the same request.",
  "298":
    "This order has already been released or voided therefore new transaction associations cannot be accepted.",
  "300": "The device ID is invalid.",
  "301": "The device batch ID is invalid.",
  "302": "The reversal flag is invalid.",
  "303": "The device batch is full. Please close the batch.",
  "304": "The original transaction is in a closed batch.",
  "305": "The merchant is configured for auto-close.",
  "306": "The batch is already closed.",
  "307": "The reversal was processed successfully.",
  "308": "Original transaction for reversal not found.",
  "309": "The device has been disabled.",
  "310": "This transaction has already been voided.",
  "311": "This transaction has already been captured.",
  "312": "The specified security code was invalid.",
  "313": "A new security code was requested.",
  "314": "This transaction cannot be processed.",
  "315": "The credit card number is invalid.",
  "316": "Credit card expiration date is invalid.",
  "317": "The credit card has expired.",
  "318": "A duplicate transaction has been submitted.",
  "319": "The transaction cannot be found.",
  "320": "The device identifier is either not registered or not enabled.",
  "325":
    "The request data did not pass the required fields check for this application.",
  "326": "The request field(s) are either invalid or missing.",
  "327":
    "The void request failed. Either the original transaction type does not support void, or the transaction is in the process of being settled.",
  "328": "A validation error occurred at the processor.",
  "330": "V.me transactions are not accepted by this merchant.",
  "331": "The x_call_id value is missing.",
  "332": "The x_call_id value is not found or invalid.",
  "333": "A validation error was returned from V.me.",
  "334": "The V.me transaction is in an invalid state.",
  "339":
    "Use x_method to specify method or send only x_call_id or card/account information.",
  "340":
    "V.me by Visa does not support voids on captured or credit transactions. Please allow the transaction to settle, then process a refund for the captured transaction.",
  "341": "The x_discount value is invalid.",
  "342": "The x_giftwrap value is invalid.",
  "343": "The x_subtotal value is invalid.",
  "344": "The x_misc value is invalid.",
  "350": "Country must be a valid two or three-character value if specified.",
  "351": "Employee ID must be 1 to %x characters in length.",
  "355": "An error occurred while parsing the EMV data.",
  "356":
    "EMV-based transactions are not currently supported for this processor and card type.",
  "357": "Opaque Descriptor is required.",
  "358": "EMV data is not supported with this transaction type.",
  "359": "EMV data is not supported with this market type.",
  "360": "An error occurred while decrypting the EMV data.",
  "361": "The EMV version is invalid.",
  "362": "The EMV version is required.",
  "363": "The POS Entry Mode value is invalid.",
  "370": "Signature data is too large.",
  "371": "Signature must be PNG formatted data.",
  "375": "Terminal/lane number must be numeric.",
  "380": "KSN is duplicated.",
  "901":
    "This transaction cannot be accepted at this time due to system maintenance. Please try again later.",
  "2000": "Need payer consent.",
  "2001": "PayPal transactions are not accepted by this merchant.",
  "2002": "PayPal transactions require x_version of at least 3.1.",
  "2003": "Request completed successfully",
  "2004": "Success URL is required.",
  "2005": "Cancel URL is required.",
  "2006": "Payer ID is required.",
  "2007": "This processor does not accept zero dollar authorizations.",
  "2008":
    "The referenced transaction does not meet the criteria for issuing a Continued Authorization.",
  "2009":
    "The referenced transaction does not meet the criteria for issuing a Continued Authorization w/ Auto Capture.",
  "2100": "PayPal transactions require valid URL for success_url",
  "2101": "PayPal transactions require valid URL for cancel_url",
  "2102":
    "Payment not authorized. Payment has not been authorized by the user.",
  "2103": "This transaction has already been authorized.",
  "2104":
    "The totals of the cart item amounts do not match order amounts. Be sure the total of the payment detail item parameters add up to the order total.",
  "2105": "PayPal has rejected the transaction.Invalid Payer ID.",
  "2106": "PayPal has already captured this transaction.",
  "2107":
    "PayPal has rejected the transaction. This Payer ID belongs to a different customer.",
  "2108":
    "PayPal has rejected the transaction. x_paypal_hdrimg exceeds maximum allowable length.",
  "2109":
    "PayPal has rejected the transaction. x_paypal_payflowcolor must be a 6 character hexadecimal value.",
  I00001: "Successful.",
  I00002: "The subscription has already been canceled.",
  I00003: "The record has already been deleted.",
  I00004: "No records found.",
  I00005:
    "The mobile device has been submitted for approval by the account administrator.",
  I00006: "The mobile device is approved and ready for use.",
  I00007:
    "The Payment Gateway Account service (id=8) has already been accepted.",
  I00008:
    "The Payment Gateway Account service (id=8) has already been declined.",
  I00009: "The APIUser already exists.",
  I00010: "The merchant is activated successfully.",
  I00011: "The merchant is not activated.",
  I99999:
    "This feature has not yet been completed. One day it will be but it looks like today is not that day.",
  E00001: "An error occurred during processing. Please try again.",
  E00002: "The content-type specified is not supported.",
  E00003: "An error occurred while parsing the XML request.",
  E00004: "The name of the requested API method is invalid.",
  E00005: "The transaction key or API key is invalid or not present.",
  E00006: "The API user name is invalid or not present.",
  E00007: "User authentication failed due to invalid authentication values.",
  E00008: "User authentication failed. The account or API user is inactive.",
  E00009:
    "The payment gateway account is in Test Mode. The request cannot be processed.",
  E00010:
    "User authentication failed. You do not have the appropriate permissions.",
  E00011: "Access denied. You do not have the appropriate permissions.",
  E00012: "A duplicate subscription already exists.",
  E00013: "The field is invalid.",
  E00014: "A required field is not present.",
  E00015: "The field length is invalid.",
  E00016: "The field type is invalid.",
  E00017: "The start date cannot occur in the past.",
  E00018: "The credit card expires before the subscription start date.",
  E00019: "The customer tax id or drivers license information is required.",
  E00020:
    "The payment gateway account is not enabled for eCheck.Net subscriptions.",
  E00021:
    "The payment gateway account is not enabled for credit card subscriptions.",
  E00022: "The interval length cannot exceed 365 days or 12 months.",
  E00023: "The subscription duration cannot exceed three years.",
  E00024: "Trial Occurrences is required when Trial Amount is specified.",
  E00025: "Automated Recurring Billing is not enabled.",
  E00026: "Both Trial Amount and Trial Occurrences are required.",
  E00027: "The transaction was unsuccessful.",
  E00028: "Trial Occurrences must be less than Total Occurrences.",
  E00029: "Payment information is required.",
  E00030: "The payment schedule is required.",
  E00031: "The amount is required.",
  E00032: "The start date is required.",
  E00033: "The start date cannot be changed.",
  E00034: "The interval information cannot be changed.",
  E00035: "The subscription cannot be found.",
  E00036: "The payment type cannot be changed.",
  E00037: "The subscription cannot be updated.",
  E00038: "The subscription cannot be canceled.",
  E00039: "A duplicate record already exists.",
  E00040: "The record cannot be found.",
  E00041: "One or more fields must contain a value.",
  E00042: "You cannot add more than {0} payment profiles.",
  E00043: "You cannot add more than {0} shipping addresses.",
  E00044: "Customer Information Manager is not enabled.",
  E00045: "The root node does not reference a valid XML namespace.",
  E00046: "Generic InsertNewMerchant failure.",
  E00047: "Merchant Boarding API is not enabled.",
  E00048:
    "At least one payment method must be set in payment types or an echeck service must be provided.",
  E00049: "The operation timed out before it could be completed.",
  E00050: "Sell Rates cannot be less than Buy Rates",
  E00051: "The original transaction was not issued for this payment profile.",
  E00052: "The maximum number of elements for an array {0} is {1}.",
  E00053: "Server too busy",
  E00054: "The mobile device is not registered with this merchant account.",
  E00055:
    "The mobile device has already been registered but is pending approval by the account administrator.",
  E00056: "The mobile device has been disabled for use with this account.",
  E00057:
    "The user does not have permissions to submit requests from a mobile device.",
  E00058:
    "The merchant has met or exceeded the number of pending mobile devices permitted for this account.",
  E00059: "The authentication type is not allowed for this method call.",
  E00060: "The transaction type is invalid.",
  E00061: "{0}({1}).",
  E00062: "Fatal error when calling web service.",
  E00063: "Calling web service return error.",
  E00064: "Client authorization denied.",
  E00065: "Prerequisite failed.",
  E00066: "Invalid value.",
  E00067:
    "An error occurred while parsing the XML request. Too many {0} specified.",
  E00068: "An error occurred while parsing the XML request. {0} is invalid.",
  E00069:
    "The Payment Gateway Account service (id=8) has already been accepted. Decline is not allowed.",
  E00070:
    "The Payment Gateway Account service (id=8) has already been declined. Agree is not allowed.",
  E00071: "{0} must contain data.",
  E00072: "Node {0} is required.",
  E00073: "{0} is invalid.",
  E00074: "This merchant is not associated with this reseller.",
  E00075:
    "An error occurred while parsing the XML request. Missing field(s) {0}.",
  E00076: "{0} contains invalid value.",
  E00077: "The value of {0} is too long. The length of value should be {1}",
  E00078: "Pending Status (not completed).",
  E00079: "The impersonation login ID is invalid or not present.",
  E00080: "The impersonation API Key is invalid or not present.",
  E00081: "Partner account is not authorized to impersonate the login account.",
  E00082: "Country for {0} is not valid.",
  E00083:
    "Bank payment method is not accepted for the selected business country.",
  E00084:
    "Credit card payment method is not accepted for the selected business country.",
  E00085: "State for {0} is not valid.",
  E00086: "Merchant has declined authorization to resource.",
  E00087: "No subscriptions found for the given request.",
  E00088: "ProfileIds cannot be sent when requesting CreateProfile.",
  E00089: "Payment data is required when requesting CreateProfile.",
  E00090: "PaymentProfile cannot be sent with payment data.",
  E00091: "PaymentProfileId cannot be sent with payment data.",
  E00092: "ShippingProfileId cannot be sent with ShipTo data.",
  E00093: "PaymentProfile cannot be sent with billing data.",
  E00094: "Paging Offset exceeds the maximum allowed value.",
  E00095: "ShippingProfileId is not provided within Customer Profile.",
  E00096: "Finger Print value is not valid.",
  E00097: "Finger Print can't be generated.",
  E00098: "Customer Profile ID or Shipping Profile ID not found.",
  E00099: "Customer profile creation failed. This transaction ID is invalid.",
  E00100:
    "Customer profile creation failed. This transaction type does not support profile creation.",
  E00101: "Customer profile creation failed.",
  E00102: "Customer Info is missing.",
  E00103:
    "Customer profile creation failed. This payment method does not support profile creation.",
  E00104: "Server in maintenance. Please try again later.",
  E00105:
    "The specified payment profile is associated with an active or suspended subscription and cannot be deleted.",
  E00106:
    "The specified customer profile is associated with an active or suspended subscription and cannot be deleted.",
  E00107:
    "The specified shipping profile is associated with an active or suspended subscription and cannot be deleted.",
  E00108: "CustomerProfileId cannot be sent with customer data.",
  E00109: "CustomerAddressId cannot be sent with shipTo data.",
  E00110: "CustomerPaymentProfileId is not provided within Customer Profile.",
  E00111:
    "The original subscription was not created with this Customer Profile.",
  E00112: "The specified month should not be in the future.",
  E00113: "Invalid OTS Token Data.",
  E00114: "Invalid OTS Token.",
  E00115: "Expired OTS Token.",
  E00116: "OTS Token access violation",
  E00117: "OTS Service Error '{0}'",
  E00118: "The transaction has been declined.",
  E00119:
    "Payment information should not be sent to Hosted Payment Page request.",
  E00120:
    "Payment and Shipping Profile IDs cannot be specified when creating new profiles.",
  E00121: "No default payment/shipping profile found.",
  E00122:
    "Please use Merchant Interface settings (API Credentials and Keys) to generate a signature key.",
  E00123: "The provided access token has expired",
  E00124: "The provided access token is invalid",
  E00125: "Hash doesnâ€™t match",
  E00126: "Failed shared key validation",
  E00127: "Invoice does not exist",
  E00128: "Requested action is not allowed",
  E00129: "Failed sending email",
  E00130: "Valid Customer Profile ID or Email is required",
  E00131: "Invoice created but not processed completely",
  E00132: "Invoicing or CIM service is not enabled.",
  E00133: "Server error.",
  E00134: "Due date is invalid",
  E00135: "Merchant has not provided processor information.",
  E00136: "Processor account is still in process, please try again later.",
  E00137: "Multiple payment types are not allowed.",
  E00138:
    "Payment and Shipping Profile IDs cannot be specified when requesting a hosted payment page.",
  E00139:
    "Access denied. Access Token does not have correct permissions for this API.",
  E00140: "Reference Id not found",
  E00141:
    "Payment Profile creation with this OpaqueData descriptor requires transactionMode to be set to liveMode.",
  E00142:
    "RecurringBilling setting is a required field for recurring tokenized payment transactions.",
  E00143: "Failed to parse MerchantId to integer",
  E00144:
    "We are currently holding the last transaction for review. Before you reactivate the subscription, review the transaction.",
  E00145:
    "This invoice has been canceled by the sender. Please contact the sender directly if you have questions. "
};
